"""Public builder and execution contracts generated from current source."""

# Generated by scripts/generate_stubs.py; do not edit signatures manually.
from collections.abc import Awaitable, Callable, Sequence
from typing import Any, overload

from deepagents import (
    AsyncSubAgent,
    CompiledSubAgent,
    DeepAgentState,
    FilesystemPermission,
)
from deepagents.backends import BackendProtocol
from langchain.agents.middleware import AgentMiddleware, InterruptOnConfig
from langchain.agents.middleware.types import ResponseT, StateT_co
from langchain.agents.structured_output import ResponseFormat
from langchain_core.language_models import BaseChatModel
from langchain_core.messages import SystemMessage
from langchain_core.tools import BaseTool
from langgraph.cache.base import BaseCache
from langgraph.checkpoint.base import BaseCheckpointSaver
from langgraph.store.base import BaseStore
from langgraph.typing import ContextT

from tinkerfin_contracts import AgentRunPreparation, Workspace
from tinkerfin_contracts import ContextKind as ContextKind
from tinkerfin_contracts import RunIdentity as RunIdentity
from tinkerfin_contracts import RuntimeObserver as _RuntimeObserver

from ._call_observation import TraceContribution as TraceContribution
from ._call_observation import trace_contribution as trace_contribution
from ._lazy_run import AgUiRunStream as AgUiRunStream
from ._lazy_run import NativeRunStream as NativeRunStream
from ._terminal_observer import TerminalObserver as _TerminalObserver
from .agui_input import AgUiUserInput as AgUiUserInput
from .agui_resume import AgUiResumeBinding as AgUiResumeBinding
from .agui_resume import AgUiResumeCheckpoint as AgUiResumeCheckpoint
from .agui_resume import AgUiResumeCheckpointObserver as AgUiResumeCheckpointObserver
from .agui_resume import AgUiResumeNotSavedObserver as AgUiResumeNotSavedObserver
from .agui_resume import AgUiResumeRequest as AgUiResumeRequest
from .errors import AgUiResumeBindingError as AgUiResumeBindingError
from .errors import RunObservationError as RunObservationError
from .errors import TinkerFinError as TinkerFinError
from .errors import TinkerFinErrorCode as TinkerFinErrorCode
from .errors import TinkerFinLifecycleError as TinkerFinLifecycleError
from .errors import TinkerFinStreamProtocolError as TinkerFinStreamProtocolError
from .media import AttachmentImage as AttachmentImage
from .media import AttachmentSupport as AttachmentSupport
from .plan import AgentMode as AgentMode
from .plan import ClarificationFormBase as _ClarificationFormBase
from .plan import ClarificationType as _ClarificationType
from .plan import DefaultClarificationForm as _DefaultClarificationForm
from .plan import PlanContentModel as _PlanContentModel
from .plan import PlanReviewAction as _PlanReviewAction
from .plan import StructuredPlanContent as _StructuredPlanContent
from .plan._config import (
    DEFAULT_ALLOWED_REVIEW_ACTIONS as _DEFAULT_ALLOWED_REVIEW_ACTIONS,
)
from .runtime import AgentRuntime as AgentRuntime
from .runtime import AgUiSettlementTimeoutError as AgUiSettlementTimeoutError
from .runtime import EventObserver as EventObserver
from .runtime import NativeStreamPart as NativeStreamPart
from .runtime import PartObserver as PartObserver
from .runtime import SseBody as SseBody
from .runtime import SseEventIdResolver as SseEventIdResolver
from .runtime import SseMapper as SseMapper
from .runtime import SsePayload as SsePayload
from .runtime import SsePreflight as SsePreflight
from .runtime import TinkerFin as _RuntimeTinkerFin
from .subagents import SubAgent, WorkspaceT

class TinkerFin(_RuntimeTinkerFin):
    """Configure resources, choose a namespace, and build a Runtime."""
    def with_namespace(self, namespace: str) -> TinkerFin:
        """Return an independent builder using the host's isolation namespace.

        Args:
            namespace: Opaque, case-sensitive namespace selected by the application.

        Returns:
            A builder borrowing the same resources and retaining other options.

        Raises:
            TypeError: The namespace is not a string.
            ValueError: The namespace is empty, padded, too long, or not UTF-8 encodable."""
        ...
    def with_attachments(self, support: AttachmentSupport) -> TinkerFin:
        """Configure authorized attachment access for the selected models.

        Automatic integration requires the locked native Deep Agents factory.
        Decorated or replaced factories are rejected at graph construction before
        model/backend preparation. Caller-owned custom graphs can install the
        support's middleware explicitly at their final model-request boundary.

        Args:
            support: Borrowed per-model image policy and host-authorized file reader.

        Returns:
            An independent builder retaining its namespace and other options.

        Raises:
            TypeError: Support is not an AttachmentSupport instance."""
        ...
    def with_observer(
        self,
        observer: _RuntimeObserver | None = None,
        *,
        on_terminal: _TerminalObserver | None = None,
    ) -> TinkerFin:
        """Observe runs with a full observer or an asynchronous terminal callback.

        Callbacks run in this process and are awaited. Their failures propagate without
        changing the selected outcome. Terminal notification can precede final cleanup.

        Args:
            observer: Borrowed observer opening one session per admitted run.
            on_terminal: Callback receiving the selected run outcome once. Exclusive
                with observer; it does not provide durable notification delivery.

        Returns:
            An independent builder retaining its namespace and other options.

        Raises:
            TypeError: The observer or callback has an invalid type.
            ValueError: Neither or both options are set, or an observer is duplicated."""
        ...
    def with_plan(
        self,
        *,
        enabled: bool = True,
        default_mode: AgentMode = "default",
        planner_model: str | BaseChatModel | None = None,
        clarification_schema: type[_ClarificationFormBase] = _DefaultClarificationForm,
        clarification_types: Sequence[_ClarificationType[Any, Any]] = (),
        content_schema: type[_PlanContentModel] = _StructuredPlanContent,
        allowed_review_actions: Sequence[
            _PlanReviewAction
        ] = _DEFAULT_ALLOWED_REVIEW_ACTIONS,
    ) -> TinkerFin:
        """Configure planning with read-only tools and human review.

        Existing builders and Runtimes retain their configuration. The returned
        builder borrows the same shared resources.

        Args:
            enabled: Whether built Runtimes support planning.
            default_mode: Mode used when execution does not select one.
            planner_model: Optional model dedicated to read-only planning.
            clarification_schema: Concrete host form used by the Planner.
            clarification_types: Additional custom semantic question types.
            content_schema: Concrete content model used for drafts and confirmed Plans.
            allowed_review_actions: Ordered decisions accepted for each Plan draft
                review.

        Returns:
            An independent builder retaining its namespace and other options.

        Raises:
            TypeError: ``enabled``, a model, or a review action has the wrong type.
            PlanModeConfigurationError: A mode or disabled configuration is invalid."""
        ...
    @overload
    def build(
        self,
        model: str | BaseChatModel | None = None,
        tools: Sequence[BaseTool | Callable[..., Any] | dict[str, Any]] | None = None,
        *,
        system_prompt: str | SystemMessage | None = None,
        middleware: Sequence[AgentMiddleware[StateT_co, ContextT]] = (),
        subagents: Sequence[SubAgent[WorkspaceT] | CompiledSubAgent | AsyncSubAgent]
        | None = None,
        skills: list[str] | None = None,
        memory: list[str] | None = None,
        permissions: list[FilesystemPermission] | None = None,
        backend: Workspace[WorkspaceT, BackendProtocol],
        prepare_tools: Callable[
            [AgentRunPreparation[WorkspaceT]], Awaitable[Sequence[BaseTool]]
        ]
        | None = None,
        interrupt_on: dict[str, bool | InterruptOnConfig] | None = None,
        response_format: ResponseFormat[ResponseT]
        | type[ResponseT]
        | dict[str, Any]
        | None = None,
        state_schema: type[DeepAgentState] | None = None,
        context_schema: type[ContextT],
        checkpointer: BaseCheckpointSaver[Any] | bool | None = None,
        store: BaseStore | None = None,
        debug: bool = False,
        name: str | None = None,
        cache: BaseCache[Any] | None = None,
    ) -> AgentRuntime[ContextT]:
        """Build an AgentRuntime with the selected model and capabilities.

        Configuration containers are copied; models, stores, backends, middleware,
        and other supplied resources remain borrowed. Building performs no execution
        I/O. Each admitted run prepares its own Graph and closes its owned resources.

        Args:
            model: Chat model instance or provider:model identifier.
            tools: Additional tools available to the agent.
            system_prompt: Instructions supplied to the model.
            middleware: Additional agent behavior and request processing. Built-in
                Store-backed middleware must use the Runtime store, without binding
                a separate store. Their file operations use asynchronous Store I/O.
            subagents: Declarative, compiled, or remote agents available for delegation.
            skills: Backend directories containing agent skills.
            memory: Backend files loaded as persistent instructions.
            permissions: Rules for filesystem tools; these do not restrict arbitrary
                shell commands. The Planner reads only allowed files; read rules
                requiring approval deny access during planning.
            backend: Borrowed filesystem capabilities or a lazy Workspace declaration.
            prepare_tools: Async function returning this agent's additional tools for
                the Run. Receives its identity and borrowed workspace (None without a
                Workspace). Names must be unique among this role's explicit tools,
                middleware, and prepared tools. Other roles do not inherit these
                tools; declarative subagents can register their own.
                Built-in file, Todo, and task tool names are reserved in every role.
            interrupt_on: Tools requiring human decisions before execution.
            response_format: Optional structured response schema or strategy.
            state_schema: Additional state fields for this agent.
            context_schema: Type of the context supplied to execution methods.
            checkpointer: Borrowed saver overriding the builder's default. False
                disables saving; True requires checkpoint inheritance from a parent.
            store: Borrowed long-term memory store. All graph access uses paths
                relative to this Runtime's namespace; synchronous access is rejected.
            debug: Whether the agent enables upstream diagnostics.
            name: Optional agent name.
            cache: Borrowed cache for graph computation.

        Returns:
            A reusable Runtime bound to this namespace and context schema.

        Raises:
            TypeError: Build arguments or their types violate the selected integration.
            ValueError: Namespace is missing or configuration is inconsistent."""
        ...
    @overload
    def build(
        self,
        model: str | BaseChatModel | None = None,
        tools: Sequence[BaseTool | Callable[..., Any] | dict[str, Any]] | None = None,
        *,
        system_prompt: str | SystemMessage | None = None,
        middleware: Sequence[AgentMiddleware[StateT_co, ContextT]] = (),
        subagents: Sequence[SubAgent[WorkspaceT] | CompiledSubAgent | AsyncSubAgent]
        | None = None,
        skills: list[str] | None = None,
        memory: list[str] | None = None,
        permissions: list[FilesystemPermission] | None = None,
        backend: Workspace[WorkspaceT, BackendProtocol],
        prepare_tools: Callable[
            [AgentRunPreparation[WorkspaceT]], Awaitable[Sequence[BaseTool]]
        ]
        | None = None,
        interrupt_on: dict[str, bool | InterruptOnConfig] | None = None,
        response_format: ResponseFormat[ResponseT]
        | type[ResponseT]
        | dict[str, Any]
        | None = None,
        state_schema: type[DeepAgentState] | None = None,
        context_schema: None = None,
        checkpointer: BaseCheckpointSaver[Any] | bool | None = None,
        store: BaseStore | None = None,
        debug: bool = False,
        name: str | None = None,
        cache: BaseCache[Any] | None = None,
    ) -> AgentRuntime[None]:
        """Build an AgentRuntime with the selected model and capabilities.

        Configuration containers are copied; models, stores, backends, middleware,
        and other supplied resources remain borrowed. Building performs no execution
        I/O. Each admitted run prepares its own Graph and closes its owned resources.

        Args:
            model: Chat model instance or provider:model identifier.
            tools: Additional tools available to the agent.
            system_prompt: Instructions supplied to the model.
            middleware: Additional agent behavior and request processing. Built-in
                Store-backed middleware must use the Runtime store, without binding
                a separate store. Their file operations use asynchronous Store I/O.
            subagents: Declarative, compiled, or remote agents available for delegation.
            skills: Backend directories containing agent skills.
            memory: Backend files loaded as persistent instructions.
            permissions: Rules for filesystem tools; these do not restrict arbitrary
                shell commands. The Planner reads only allowed files; read rules
                requiring approval deny access during planning.
            backend: Borrowed filesystem capabilities or a lazy Workspace declaration.
            prepare_tools: Async function returning this agent's additional tools for
                the Run. Receives its identity and borrowed workspace (None without a
                Workspace). Names must be unique among this role's explicit tools,
                middleware, and prepared tools. Other roles do not inherit these
                tools; declarative subagents can register their own.
                Built-in file, Todo, and task tool names are reserved in every role.
            interrupt_on: Tools requiring human decisions before execution.
            response_format: Optional structured response schema or strategy.
            state_schema: Additional state fields for this agent.
            context_schema: Type of the context supplied to execution methods.
            checkpointer: Borrowed saver overriding the builder's default. False
                disables saving; True requires checkpoint inheritance from a parent.
            store: Borrowed long-term memory store. All graph access uses paths
                relative to this Runtime's namespace; synchronous access is rejected.
            debug: Whether the agent enables upstream diagnostics.
            name: Optional agent name.
            cache: Borrowed cache for graph computation.

        Returns:
            A reusable Runtime bound to this namespace and context schema.

        Raises:
            TypeError: Build arguments or their types violate the selected integration.
            ValueError: Namespace is missing or configuration is inconsistent."""
        ...
    @overload
    def build(
        self,
        model: str | BaseChatModel | None = None,
        tools: Sequence[BaseTool | Callable[..., Any] | dict[str, Any]] | None = None,
        *,
        system_prompt: str | SystemMessage | None = None,
        middleware: Sequence[AgentMiddleware[StateT_co, ContextT]] = (),
        subagents: Sequence[SubAgent[None] | CompiledSubAgent | AsyncSubAgent]
        | None = None,
        skills: list[str] | None = None,
        memory: list[str] | None = None,
        permissions: list[FilesystemPermission] | None = None,
        backend: BackendProtocol | None = None,
        prepare_tools: Callable[
            [AgentRunPreparation[None]], Awaitable[Sequence[BaseTool]]
        ]
        | None = None,
        interrupt_on: dict[str, bool | InterruptOnConfig] | None = None,
        response_format: ResponseFormat[ResponseT]
        | type[ResponseT]
        | dict[str, Any]
        | None = None,
        state_schema: type[DeepAgentState] | None = None,
        context_schema: type[ContextT],
        checkpointer: BaseCheckpointSaver[Any] | bool | None = None,
        store: BaseStore | None = None,
        debug: bool = False,
        name: str | None = None,
        cache: BaseCache[Any] | None = None,
    ) -> AgentRuntime[ContextT]:
        """Build an AgentRuntime with the selected model and capabilities.

        Configuration containers are copied; models, stores, backends, middleware,
        and other supplied resources remain borrowed. Building performs no execution
        I/O. Each admitted run prepares its own Graph and closes its owned resources.

        Args:
            model: Chat model instance or provider:model identifier.
            tools: Additional tools available to the agent.
            system_prompt: Instructions supplied to the model.
            middleware: Additional agent behavior and request processing. Built-in
                Store-backed middleware must use the Runtime store, without binding
                a separate store. Their file operations use asynchronous Store I/O.
            subagents: Declarative, compiled, or remote agents available for delegation.
            skills: Backend directories containing agent skills.
            memory: Backend files loaded as persistent instructions.
            permissions: Rules for filesystem tools; these do not restrict arbitrary
                shell commands. The Planner reads only allowed files; read rules
                requiring approval deny access during planning.
            backend: Borrowed filesystem capabilities or a lazy Workspace declaration.
            prepare_tools: Async function returning this agent's additional tools for
                the Run. Receives its identity and borrowed workspace (None without a
                Workspace). Names must be unique among this role's explicit tools,
                middleware, and prepared tools. Other roles do not inherit these
                tools; declarative subagents can register their own.
                Built-in file, Todo, and task tool names are reserved in every role.
            interrupt_on: Tools requiring human decisions before execution.
            response_format: Optional structured response schema or strategy.
            state_schema: Additional state fields for this agent.
            context_schema: Type of the context supplied to execution methods.
            checkpointer: Borrowed saver overriding the builder's default. False
                disables saving; True requires checkpoint inheritance from a parent.
            store: Borrowed long-term memory store. All graph access uses paths
                relative to this Runtime's namespace; synchronous access is rejected.
            debug: Whether the agent enables upstream diagnostics.
            name: Optional agent name.
            cache: Borrowed cache for graph computation.

        Returns:
            A reusable Runtime bound to this namespace and context schema.

        Raises:
            TypeError: Build arguments or their types violate the selected integration.
            ValueError: Namespace is missing or configuration is inconsistent."""
        ...
    @overload
    def build(
        self,
        model: str | BaseChatModel | None = None,
        tools: Sequence[BaseTool | Callable[..., Any] | dict[str, Any]] | None = None,
        *,
        system_prompt: str | SystemMessage | None = None,
        middleware: Sequence[AgentMiddleware[StateT_co, ContextT]] = (),
        subagents: Sequence[SubAgent[None] | CompiledSubAgent | AsyncSubAgent]
        | None = None,
        skills: list[str] | None = None,
        memory: list[str] | None = None,
        permissions: list[FilesystemPermission] | None = None,
        backend: BackendProtocol | None = None,
        prepare_tools: Callable[
            [AgentRunPreparation[None]], Awaitable[Sequence[BaseTool]]
        ]
        | None = None,
        interrupt_on: dict[str, bool | InterruptOnConfig] | None = None,
        response_format: ResponseFormat[ResponseT]
        | type[ResponseT]
        | dict[str, Any]
        | None = None,
        state_schema: type[DeepAgentState] | None = None,
        context_schema: None = None,
        checkpointer: BaseCheckpointSaver[Any] | bool | None = None,
        store: BaseStore | None = None,
        debug: bool = False,
        name: str | None = None,
        cache: BaseCache[Any] | None = None,
    ) -> AgentRuntime[None]:
        """Build an AgentRuntime with the selected model and capabilities.

        Configuration containers are copied; models, stores, backends, middleware,
        and other supplied resources remain borrowed. Building performs no execution
        I/O. Each admitted run prepares its own Graph and closes its owned resources.

        Args:
            model: Chat model instance or provider:model identifier.
            tools: Additional tools available to the agent.
            system_prompt: Instructions supplied to the model.
            middleware: Additional agent behavior and request processing. Built-in
                Store-backed middleware must use the Runtime store, without binding
                a separate store. Their file operations use asynchronous Store I/O.
            subagents: Declarative, compiled, or remote agents available for delegation.
            skills: Backend directories containing agent skills.
            memory: Backend files loaded as persistent instructions.
            permissions: Rules for filesystem tools; these do not restrict arbitrary
                shell commands. The Planner reads only allowed files; read rules
                requiring approval deny access during planning.
            backend: Borrowed filesystem capabilities or a lazy Workspace declaration.
            prepare_tools: Async function returning this agent's additional tools for
                the Run. Receives its identity and borrowed workspace (None without a
                Workspace). Names must be unique among this role's explicit tools,
                middleware, and prepared tools. Other roles do not inherit these
                tools; declarative subagents can register their own.
                Built-in file, Todo, and task tool names are reserved in every role.
            interrupt_on: Tools requiring human decisions before execution.
            response_format: Optional structured response schema or strategy.
            state_schema: Additional state fields for this agent.
            context_schema: Type of the context supplied to execution methods.
            checkpointer: Borrowed saver overriding the builder's default. False
                disables saving; True requires checkpoint inheritance from a parent.
            store: Borrowed long-term memory store. All graph access uses paths
                relative to this Runtime's namespace; synchronous access is rejected.
            debug: Whether the agent enables upstream diagnostics.
            name: Optional agent name.
            cache: Borrowed cache for graph computation.

        Returns:
            A reusable Runtime bound to this namespace and context schema.

        Raises:
            TypeError: Build arguments or their types violate the selected integration.
            ValueError: Namespace is missing or configuration is inconsistent."""
        ...

__all__: list[str]
