"""Typed callable contract for the actual Runtime build descriptor."""

# Generated by scripts/generate_stubs.py; do not edit signatures manually.
from __future__ import annotations

from collections.abc import Awaitable, Callable, Sequence
from typing import Any, Protocol, overload

from deepagents import (
    AsyncSubAgent,
    CompiledSubAgent,
    DeepAgentState,
    FilesystemPermission,
)
from deepagents.backends import BackendProtocol
from langchain.agents.middleware import AgentMiddleware, InterruptOnConfig
from langchain.agents.middleware.types import ResponseT, StateT_co
from langchain.agents.structured_output import ResponseFormat
from langchain_core.language_models import BaseChatModel
from langchain_core.messages import SystemMessage
from langchain_core.tools import BaseTool
from langgraph.cache.base import BaseCache
from langgraph.checkpoint.base import BaseCheckpointSaver
from langgraph.store.base import BaseStore
from langgraph.typing import ContextT

from tinkerfin_contracts import AgentRunPreparation, Workspace

from .runtime import AgentRuntime
from .subagents import SubAgent, WorkspaceT


class BuildAgent(Protocol):
    """Build a Runtime whose execution context matches context_schema."""

    @overload
    def __call__(
        self,
        model: str | BaseChatModel | None = None,
        tools: Sequence[BaseTool | Callable[..., Any] | dict[str, Any]] | None = None,
        *,
        system_prompt: str | SystemMessage | None = None,
        middleware: Sequence[AgentMiddleware[StateT_co, ContextT]] = (),
        subagents: Sequence[SubAgent[WorkspaceT] | CompiledSubAgent | AsyncSubAgent]
        | None = None,
        skills: list[str] | None = None,
        memory: list[str] | None = None,
        permissions: list[FilesystemPermission] | None = None,
        backend: Workspace[WorkspaceT, BackendProtocol],
        prepare_tools: Callable[
            [AgentRunPreparation[WorkspaceT]], Awaitable[Sequence[BaseTool]]
        ]
        | None = None,
        interrupt_on: dict[str, bool | InterruptOnConfig] | None = None,
        response_format: ResponseFormat[ResponseT]
        | type[ResponseT]
        | dict[str, Any]
        | None = None,
        state_schema: type[DeepAgentState] | None = None,
        context_schema: type[ContextT],
        checkpointer: BaseCheckpointSaver[Any] | bool | None = None,
        store: BaseStore | None = None,
        debug: bool = False,
        name: str | None = None,
        cache: BaseCache[Any] | None = None,
    ) -> AgentRuntime[ContextT]:
        """Build an AgentRuntime with the selected model and capabilities.

        Configuration containers are copied; models, stores, backends, middleware,
        and other supplied resources remain borrowed. Building performs no execution
        I/O. Each admitted run prepares its own Graph and closes its owned resources.

        Args:
            model: Chat model instance or provider:model identifier.
            tools: Additional tools available to the agent.
            system_prompt: Instructions supplied to the model.
            middleware: Additional agent behavior and request processing. Built-in
                Store-backed middleware must use the Runtime store, without binding
                a separate store. Their file operations use asynchronous Store I/O.
            subagents: Declarative, compiled, or remote agents available for delegation.
            skills: Backend directories containing agent skills.
            memory: Backend files loaded as persistent instructions.
            permissions: Rules for filesystem tools; these do not restrict arbitrary
                shell commands. The Planner reads only allowed files; read rules
                requiring approval deny access during planning.
            backend: Borrowed filesystem capabilities or a lazy Workspace declaration.
            prepare_tools: Async function returning this agent's additional tools for
                the Run. Receives its identity and borrowed workspace (None without a
                Workspace). Names must be unique among this role's explicit tools,
                middleware, and prepared tools. Other roles do not inherit these
                tools; declarative subagents can register their own.
                Built-in file, Todo, and task tool names are reserved in every role.
            interrupt_on: Tools requiring human decisions before execution.
            response_format: Optional structured response schema or strategy.
            state_schema: Additional state fields for this agent.
            context_schema: Type of the context supplied to execution methods.
            checkpointer: Borrowed saver overriding the builder's default. False
                disables saving; True requires checkpoint inheritance from a parent.
            store: Borrowed long-term memory store. All graph access uses paths
                relative to this Runtime's namespace; synchronous access is rejected.
            debug: Whether the agent enables upstream diagnostics.
            name: Optional agent name.
            cache: Borrowed cache for graph computation.

        Returns:
            A reusable Runtime bound to this namespace and context schema.

        Raises:
            TypeError: Build arguments or their types violate the selected integration.
            ValueError: Namespace is missing or configuration is inconsistent."""
        ...

    @overload
    def __call__(
        self,
        model: str | BaseChatModel | None = None,
        tools: Sequence[BaseTool | Callable[..., Any] | dict[str, Any]] | None = None,
        *,
        system_prompt: str | SystemMessage | None = None,
        middleware: Sequence[AgentMiddleware[StateT_co, ContextT]] = (),
        subagents: Sequence[SubAgent[WorkspaceT] | CompiledSubAgent | AsyncSubAgent]
        | None = None,
        skills: list[str] | None = None,
        memory: list[str] | None = None,
        permissions: list[FilesystemPermission] | None = None,
        backend: Workspace[WorkspaceT, BackendProtocol],
        prepare_tools: Callable[
            [AgentRunPreparation[WorkspaceT]], Awaitable[Sequence[BaseTool]]
        ]
        | None = None,
        interrupt_on: dict[str, bool | InterruptOnConfig] | None = None,
        response_format: ResponseFormat[ResponseT]
        | type[ResponseT]
        | dict[str, Any]
        | None = None,
        state_schema: type[DeepAgentState] | None = None,
        context_schema: None = None,
        checkpointer: BaseCheckpointSaver[Any] | bool | None = None,
        store: BaseStore | None = None,
        debug: bool = False,
        name: str | None = None,
        cache: BaseCache[Any] | None = None,
    ) -> AgentRuntime[None]:
        """Build an AgentRuntime with the selected model and capabilities.

        Configuration containers are copied; models, stores, backends, middleware,
        and other supplied resources remain borrowed. Building performs no execution
        I/O. Each admitted run prepares its own Graph and closes its owned resources.

        Args:
            model: Chat model instance or provider:model identifier.
            tools: Additional tools available to the agent.
            system_prompt: Instructions supplied to the model.
            middleware: Additional agent behavior and request processing. Built-in
                Store-backed middleware must use the Runtime store, without binding
                a separate store. Their file operations use asynchronous Store I/O.
            subagents: Declarative, compiled, or remote agents available for delegation.
            skills: Backend directories containing agent skills.
            memory: Backend files loaded as persistent instructions.
            permissions: Rules for filesystem tools; these do not restrict arbitrary
                shell commands. The Planner reads only allowed files; read rules
                requiring approval deny access during planning.
            backend: Borrowed filesystem capabilities or a lazy Workspace declaration.
            prepare_tools: Async function returning this agent's additional tools for
                the Run. Receives its identity and borrowed workspace (None without a
                Workspace). Names must be unique among this role's explicit tools,
                middleware, and prepared tools. Other roles do not inherit these
                tools; declarative subagents can register their own.
                Built-in file, Todo, and task tool names are reserved in every role.
            interrupt_on: Tools requiring human decisions before execution.
            response_format: Optional structured response schema or strategy.
            state_schema: Additional state fields for this agent.
            context_schema: Type of the context supplied to execution methods.
            checkpointer: Borrowed saver overriding the builder's default. False
                disables saving; True requires checkpoint inheritance from a parent.
            store: Borrowed long-term memory store. All graph access uses paths
                relative to this Runtime's namespace; synchronous access is rejected.
            debug: Whether the agent enables upstream diagnostics.
            name: Optional agent name.
            cache: Borrowed cache for graph computation.

        Returns:
            A reusable Runtime bound to this namespace and context schema.

        Raises:
            TypeError: Build arguments or their types violate the selected integration.
            ValueError: Namespace is missing or configuration is inconsistent."""
        ...

    @overload
    def __call__(
        self,
        model: str | BaseChatModel | None = None,
        tools: Sequence[BaseTool | Callable[..., Any] | dict[str, Any]] | None = None,
        *,
        system_prompt: str | SystemMessage | None = None,
        middleware: Sequence[AgentMiddleware[StateT_co, ContextT]] = (),
        subagents: Sequence[SubAgent[None] | CompiledSubAgent | AsyncSubAgent]
        | None = None,
        skills: list[str] | None = None,
        memory: list[str] | None = None,
        permissions: list[FilesystemPermission] | None = None,
        backend: BackendProtocol | None = None,
        prepare_tools: Callable[
            [AgentRunPreparation[None]], Awaitable[Sequence[BaseTool]]
        ]
        | None = None,
        interrupt_on: dict[str, bool | InterruptOnConfig] | None = None,
        response_format: ResponseFormat[ResponseT]
        | type[ResponseT]
        | dict[str, Any]
        | None = None,
        state_schema: type[DeepAgentState] | None = None,
        context_schema: type[ContextT],
        checkpointer: BaseCheckpointSaver[Any] | bool | None = None,
        store: BaseStore | None = None,
        debug: bool = False,
        name: str | None = None,
        cache: BaseCache[Any] | None = None,
    ) -> AgentRuntime[ContextT]:
        """Build an AgentRuntime with the selected model and capabilities.

        Configuration containers are copied; models, stores, backends, middleware,
        and other supplied resources remain borrowed. Building performs no execution
        I/O. Each admitted run prepares its own Graph and closes its owned resources.

        Args:
            model: Chat model instance or provider:model identifier.
            tools: Additional tools available to the agent.
            system_prompt: Instructions supplied to the model.
            middleware: Additional agent behavior and request processing. Built-in
                Store-backed middleware must use the Runtime store, without binding
                a separate store. Their file operations use asynchronous Store I/O.
            subagents: Declarative, compiled, or remote agents available for delegation.
            skills: Backend directories containing agent skills.
            memory: Backend files loaded as persistent instructions.
            permissions: Rules for filesystem tools; these do not restrict arbitrary
                shell commands. The Planner reads only allowed files; read rules
                requiring approval deny access during planning.
            backend: Borrowed filesystem capabilities or a lazy Workspace declaration.
            prepare_tools: Async function returning this agent's additional tools for
                the Run. Receives its identity and borrowed workspace (None without a
                Workspace). Names must be unique among this role's explicit tools,
                middleware, and prepared tools. Other roles do not inherit these
                tools; declarative subagents can register their own.
                Built-in file, Todo, and task tool names are reserved in every role.
            interrupt_on: Tools requiring human decisions before execution.
            response_format: Optional structured response schema or strategy.
            state_schema: Additional state fields for this agent.
            context_schema: Type of the context supplied to execution methods.
            checkpointer: Borrowed saver overriding the builder's default. False
                disables saving; True requires checkpoint inheritance from a parent.
            store: Borrowed long-term memory store. All graph access uses paths
                relative to this Runtime's namespace; synchronous access is rejected.
            debug: Whether the agent enables upstream diagnostics.
            name: Optional agent name.
            cache: Borrowed cache for graph computation.

        Returns:
            A reusable Runtime bound to this namespace and context schema.

        Raises:
            TypeError: Build arguments or their types violate the selected integration.
            ValueError: Namespace is missing or configuration is inconsistent."""
        ...

    @overload
    def __call__(
        self,
        model: str | BaseChatModel | None = None,
        tools: Sequence[BaseTool | Callable[..., Any] | dict[str, Any]] | None = None,
        *,
        system_prompt: str | SystemMessage | None = None,
        middleware: Sequence[AgentMiddleware[StateT_co, ContextT]] = (),
        subagents: Sequence[SubAgent[None] | CompiledSubAgent | AsyncSubAgent]
        | None = None,
        skills: list[str] | None = None,
        memory: list[str] | None = None,
        permissions: list[FilesystemPermission] | None = None,
        backend: BackendProtocol | None = None,
        prepare_tools: Callable[
            [AgentRunPreparation[None]], Awaitable[Sequence[BaseTool]]
        ]
        | None = None,
        interrupt_on: dict[str, bool | InterruptOnConfig] | None = None,
        response_format: ResponseFormat[ResponseT]
        | type[ResponseT]
        | dict[str, Any]
        | None = None,
        state_schema: type[DeepAgentState] | None = None,
        context_schema: None = None,
        checkpointer: BaseCheckpointSaver[Any] | bool | None = None,
        store: BaseStore | None = None,
        debug: bool = False,
        name: str | None = None,
        cache: BaseCache[Any] | None = None,
    ) -> AgentRuntime[None]:
        """Build an AgentRuntime with the selected model and capabilities.

        Configuration containers are copied; models, stores, backends, middleware,
        and other supplied resources remain borrowed. Building performs no execution
        I/O. Each admitted run prepares its own Graph and closes its owned resources.

        Args:
            model: Chat model instance or provider:model identifier.
            tools: Additional tools available to the agent.
            system_prompt: Instructions supplied to the model.
            middleware: Additional agent behavior and request processing. Built-in
                Store-backed middleware must use the Runtime store, without binding
                a separate store. Their file operations use asynchronous Store I/O.
            subagents: Declarative, compiled, or remote agents available for delegation.
            skills: Backend directories containing agent skills.
            memory: Backend files loaded as persistent instructions.
            permissions: Rules for filesystem tools; these do not restrict arbitrary
                shell commands. The Planner reads only allowed files; read rules
                requiring approval deny access during planning.
            backend: Borrowed filesystem capabilities or a lazy Workspace declaration.
            prepare_tools: Async function returning this agent's additional tools for
                the Run. Receives its identity and borrowed workspace (None without a
                Workspace). Names must be unique among this role's explicit tools,
                middleware, and prepared tools. Other roles do not inherit these
                tools; declarative subagents can register their own.
                Built-in file, Todo, and task tool names are reserved in every role.
            interrupt_on: Tools requiring human decisions before execution.
            response_format: Optional structured response schema or strategy.
            state_schema: Additional state fields for this agent.
            context_schema: Type of the context supplied to execution methods.
            checkpointer: Borrowed saver overriding the builder's default. False
                disables saving; True requires checkpoint inheritance from a parent.
            store: Borrowed long-term memory store. All graph access uses paths
                relative to this Runtime's namespace; synchronous access is rejected.
            debug: Whether the agent enables upstream diagnostics.
            name: Optional agent name.
            cache: Borrowed cache for graph computation.

        Returns:
            A reusable Runtime bound to this namespace and context schema.

        Raises:
            TypeError: Build arguments or their types violate the selected integration.
            ValueError: Namespace is missing or configuration is inconsistent."""
        ...
